concurrent = {{runner.concurrent if runner.concurrent is defined else "1"}}
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[[runners]]
  name = "{{runner.name}}"
  url = "{{runner.url}}"
  token = "{{runner.token|default('set me')}}"
  executor = "{{runner.executor}}"
  builds_dir = "{{runner.builds_dir|default('/builds')}}"
  cache_dir = "{{runner.cache_dir|default('/cache')}}"
{% if runner.executor == 'docker' %}
  [runners.docker]
    tls_verify = false
    host = "unix://{{runner_podman_socket}}"
{% if runner.image is defined %}
    image = "{{runner.image}}"
    {% endif %}
    privileged = {{runner.privileged if runner.privileged is defined else "false"}}
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = {{runner.volumes}}
{% endif %}
