<%namespace name="nginx" file="server.conf" />
%for (proto, server), path_services in by_server_path.items():
<%nginx:server_block name="${server}" proto="${proto}">
%for service in path_services.values():
%if service.upstream_url.scheme == 'file':
    location ${service.downstream_url.path} {
        alias ${service.upstream_url.path};
        autoindex on;
    }
%else:
    location ${service.downstream_url.path} {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
%if service.upstream_url.scheme == 'https':
        proxy_ssl_server_name on;
%if service.ssl_name:
        proxy_ssl_name ${service.ssl_name};
        proxy_ssl_verify on;
%else:
        proxy_ssl_verify off;
%endif
%endif
        proxy_pass ${service.upstream_url.geturl()};
    }
%endif
%endfor
</%nginx:server_block>
%endfor