<%def name="server_block(proto, name)">
<%
listen = 80
redirect_http = False
if proto == 'https':
    if name not in certs_by_domain:
        raise ValueError(f'https was requested but no certificate is available for {name}')
    listen = 443
    cert_info = certs_by_domain[name]
    redirect_http = True
%>
server {
    listen ${listen};
    server_name ${name};
%if proto == 'https':
    ssl_certificate ${cert_info.cert_file};
    ssl_certificate_key ${cert_info.key_file};
    add_header Strict-Transport-Security "max-age=63072000;" always;
%endif
${caller.body()}
}
%if redirect_http:
server {
    listen 80;
    server_name ${name};
    return 301 https://${name}$request_uri;
}
%endif
</%def>
